# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9062da6ec6ab82e891f3530cf278795"
name = "international-business-app"
handle = "international-business-app-17"
application_url = "https://remember-eat-kitty-additionally.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_files,read_files"

[auth]
redirect_urls = ["https://remember-eat-kitty-additionally.trycloudflare.com/auth/callback", "https://remember-eat-kitty-additionally.trycloudflare.com/auth/shopify/callback", "https://remember-eat-kitty-additionally.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
